import type { Rank, Suit } from '../../game/types';

/** Public-domain 52-card faces (CC0). https://github.com/AustinGabriel/Public-Domain-and-CC0-Playing-Cards */
export const CARD_FACES: Record<Suit, Record<Rank, number>> = {
  spades: {
    A: require('../../../assets/game/cards/spades/A.png'),
    2: require('../../../assets/game/cards/spades/2.png'),
    3: require('../../../assets/game/cards/spades/3.png'),
    4: require('../../../assets/game/cards/spades/4.png'),
    5: require('../../../assets/game/cards/spades/5.png'),
    6: require('../../../assets/game/cards/spades/6.png'),
    7: require('../../../assets/game/cards/spades/7.png'),
    8: require('../../../assets/game/cards/spades/8.png'),
    9: require('../../../assets/game/cards/spades/9.png'),
    '10': require('../../../assets/game/cards/spades/10.png'),
    J: require('../../../assets/game/cards/spades/J.png'),
    Q: require('../../../assets/game/cards/spades/Q.png'),
    K: require('../../../assets/game/cards/spades/K.png'),
  },
  hearts: {
    A: require('../../../assets/game/cards/hearts/A.png'),
    2: require('../../../assets/game/cards/hearts/2.png'),
    3: require('../../../assets/game/cards/hearts/3.png'),
    4: require('../../../assets/game/cards/hearts/4.png'),
    5: require('../../../assets/game/cards/hearts/5.png'),
    6: require('../../../assets/game/cards/hearts/6.png'),
    7: require('../../../assets/game/cards/hearts/7.png'),
    8: require('../../../assets/game/cards/hearts/8.png'),
    9: require('../../../assets/game/cards/hearts/9.png'),
    '10': require('../../../assets/game/cards/hearts/10.png'),
    J: require('../../../assets/game/cards/hearts/J.png'),
    Q: require('../../../assets/game/cards/hearts/Q.png'),
    K: require('../../../assets/game/cards/hearts/K.png'),
  },
  diamonds: {
    A: require('../../../assets/game/cards/diamonds/A.png'),
    2: require('../../../assets/game/cards/diamonds/2.png'),
    3: require('../../../assets/game/cards/diamonds/3.png'),
    4: require('../../../assets/game/cards/diamonds/4.png'),
    5: require('../../../assets/game/cards/diamonds/5.png'),
    6: require('../../../assets/game/cards/diamonds/6.png'),
    7: require('../../../assets/game/cards/diamonds/7.png'),
    8: require('../../../assets/game/cards/diamonds/8.png'),
    9: require('../../../assets/game/cards/diamonds/9.png'),
    '10': require('../../../assets/game/cards/diamonds/10.png'),
    J: require('../../../assets/game/cards/diamonds/J.png'),
    Q: require('../../../assets/game/cards/diamonds/Q.png'),
    K: require('../../../assets/game/cards/diamonds/K.png'),
  },
  clubs: {
    A: require('../../../assets/game/cards/clubs/A.png'),
    2: require('../../../assets/game/cards/clubs/2.png'),
    3: require('../../../assets/game/cards/clubs/3.png'),
    4: require('../../../assets/game/cards/clubs/4.png'),
    5: require('../../../assets/game/cards/clubs/5.png'),
    6: require('../../../assets/game/cards/clubs/6.png'),
    7: require('../../../assets/game/cards/clubs/7.png'),
    8: require('../../../assets/game/cards/clubs/8.png'),
    9: require('../../../assets/game/cards/clubs/9.png'),
    '10': require('../../../assets/game/cards/clubs/10.png'),
    J: require('../../../assets/game/cards/clubs/J.png'),
    Q: require('../../../assets/game/cards/clubs/Q.png'),
    K: require('../../../assets/game/cards/clubs/K.png'),
  },
};
